# Generated by Django 5.1.7 on 2025-03-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_description',
            field=models.TextField(default='No Description Provided'),
        ),
    ]
