# Generated by Django 5.1.7 on 2025-05-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_order_customer_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
